name: mr_guide
description: "Mr. Guide - Explore Sri Lanka mobile app"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  http: ^1.2.2
  shared_preferences: ^2.3.3
  geolocator: ^13.0.2
  url_launcher: ^6.3.1
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
